### PR TITLE
Change repository structure

### PR DESCRIPTION
**Pull request by stijnvanhoey**
This PR is a follow up of the discussion of #25 and introduces a major shift in the repository structure and setup as setup by @jorisvandenbossche and myself. We are aware this PR will break code (@twallema anticipated this with a release, see https://github.com/UGentBiomath/COVID19-Model/issues/25#issuecomment-623950425).

Besides the folder layout defined in #25 , the PR provides the following:
- The model code is part of a small in-repo Python package called `covid19model` (see the `setup.py` file), making it possible to import it like any other package you would install. In practice, to load the models you now do: `from covid19model.models import models`. In the furture we can further adjust this, but it makes it compatible to the main current `models` module. 
- A sphinx-based documentation website. We moved the most sections from the current readme to different pages of the documentation website (e.g. [model description](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/docs/models.md)). For the moment, we used the `read_the_docs` theme, which can be changed/customized later. Both `rst` and markdown files are supported. The home page looks like (locally built on my PC):

image

- We included some informative pages to get users/collaborators technically started and introduced to the tooling. For most of these, we provided 'general blueprints', which can be adjusted for this specific project: 
  - [Installation instructions](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/docs/installation.md)  - part of documentation website
  - [guidelines for collaboration](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/docs/collaborate.md) - part of documentation website
  - [contributing guidelines](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/.github/CONTRIBUTING.rst) providing a high level overview of types of contributions. - part of documentation website
  - [issue](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/.github/ISSUE_TEMPLATE.md) and [pull request](https://github.com/stijnvanhoey/COVID19-Model/blob/cookiecutter/.github/pull_request_template.md) - templates informing users when opening issue/PR in Github website.

Furthermore:
- updated `environment.yml` file with required dependencies.
- adjusted the demo notebooks (in the `templates` folder). The `SEIRSAgeModel_demo.ipynb` runs without error under the new setup. For the `SEIRSNetworkModel_demo.ipynb` notebook, some more code refactoring is required, e.g. solving #34  to make it work.
- We did not checked the other notebooks, so these won't work after merging the code. 

@Beramos @twallema and @JennaVergeynst hopefully this is in line with your ideas about the setup and this provides a good enough start with enough documentation about the setup. Comments are certainly welcome. When this is merged, we can start on the code restructuring itself next week.

__Furthermore:__
- It would be good if we could setup the `github workflow` to automatically build and deploy the documentation website. @Beramos maybe something we can do together, can be based on what I recently did for [pywaterinfo](https://github.com/fluves/pywaterinfo/tree/master/.github/workflows).

### CODE REVIEW

**Comment by JennaVergeynst** [comment]
This looks really neat and good to me! Maybe somewhere on the welcome page, a data description section would be on its place (we can fill that in from our side)

**Comment by stijnvanhoey** [comment]
> This looks really neat and good to me! Maybe somewhere on the welcome page, a data description section would be appropriate (we can fill that in from our side)

See https://github.com/UGentBiomath/COVID19-Model/issues/32 ;-)

**Comment by Beramos** [comment]
Thanks folks! This looks amazing. @stijnvanhoey I'm very interested on working with the automated generation of the documentation.  @twallema I'm going to let you merge this one whenever you are ready

**Comment by stijnvanhoey** [comment]
@twallema I see you did some development in other branches and merging them to master while this PR is open. This introduces conflicts in this PR in the notebook. Could we work towards merging both somewhere this week or was there any other element blocking you from merging this? I do think issues like https://github.com/UGentBiomath/COVID19-Model/issues/32 can be solved after merging as well.

**Comment by stijnvanhoey** [comment]
@twallema all current conflicts are fixed and the code is up to date with your latest adjustments to the network based models. Any other issue before we can merge this?

**Comment by twallema** [comment]
No issues, you can merge.

**Comment by stijnvanhoey** [comment]
Thanks. Well, I can't merge as I do not have the rights to this repo, you'll have to do that ;-)

**Comment by Beramos** [comment]
Let's go!

**Pull request merged**
