### PR TITLE
add link to documentation website in README

### LINKED ISSUE #36: Automate sphinx documentation build
@Beramos, as discussed on #35 I would update documentation on each update of the master. The file to put in the `.github/workflows` folder should look more or less like this:

```
name: Upload Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
    - name: Build documentation
      run: |
        python setup.py build_sphinx
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html
```

The main issue is that this won't install the package dependencies defined in `environment.yml`. @jorisvandenbossche -> should we put these requirements in `setup.py`as well (quickly done) or rather adjust the steps above to make it work with conda environment file (overcoming duplicate definition of dependencies)?

### PR DESCRIPTION
**Pull request by Beramos**
closes #36 

* [X] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [X] I made sure all new and existing data sets have a description in the `data/README.md` file
* [X] I have updated the documentation accordingly.

Describe your fixes/additions/changes

### CODE REVIEW

**Comment by Beramos** [comment]
@stijnvanhoey, I get an error that the github actions bot does not have the right permissions to push the sphinx build to the gh-pages branch. As far as I found out the `github_token` argument used by the *peaceiris* template should give an automatic read/write permission so I don't see where this error is coming from:

image

**Comment by jorisvandenbossche** [comment]
I think the deploy step should only run on master (where it also succeeded: https://github.com/UGentBiomath/COVID19-Model/runs/684427817), and not on each pull request (building the docs is still good to ensure it actually builds)

**Comment by jorisvandenbossche** [comment]
In the pandas github actions yml, we use `if: github.event_name == 'push'` for that specific step, so like:

```
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html 
      if: github.event_name == 'push'
```

**Comment by stijnvanhoey** [comment]
@Beramos I agree with Joris. Building on every PR (_does it work?_) versus deploying the website (only on master). I do think the `ush` trick will do the job ;-)

I would also change the first line of the workflow `name: Upload Python Package` -> e.g. `Build sphinx documentation website` as it is more informative on what is actually happening.

**Comment by Beramos** [comment]
Ok, thanks for the tips!

**Pull request merged**
