### PR TITLE
Proximus mobility functions (second attempt)

### PR DESCRIPTION
**Pull request by mrollier**
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I made sure all new and existing data sets have a description in the `data/README.md` file
* [x] I have updated the documentation accordingly.

(( copied from previous (closed) PR, which was closed because it confusingly contained commits from many months ago ))

- Add ten or so functions in `src/covid19model/data/mobility to load and clean up Proximus mobility data. All functions have clear descriptions.

- Add a Notebook "preprocessing/MR-analyse-proximus-mobility-data.ipynb" that demonstrates the use of these functions.

- Create clean mobility matrices for the average of every week on record in 2020 at the level of municipalities, arrondissements and provinces. These cannot be saved in Git because of privacy concerns. I saved these clean mobility data in data/interim/mobility and added this directory to the .gitignore, as @twallema suggested. Colleagues: please make a similar directory on your local machine and copy the processed data from our shared drive.

- Add a line in .gitignore

NOTE: I couldn't find the moving_avg definition I had made a while ago, so I copied its definition to visualization/utils.

Everything should work, but do let me know if something goes haywire.

### CODE REVIEW

**Comment by JennaVergeynst** [comment]
Looks good! Do you want also answers on the questions in your notebook, or do we discuss this in a meeting?

**Comment by mrollier** [comment]
> Looks good! Do you want also answers on the questions in your notebook, or do we discuss this in a meeting?

We can do this in the meeting cause I have to prepare this better. Something went wrong with the tests, though. I got an ominous email stating that "all jobs have failed". Note sure what to do with that info.

**Comment by JennaVergeynst** [comment]
I think the tests should be tested again ;-) @twallema any progress there?

**Comment by twallema** [comment]
@mrollier Trek even PR #229 binnen op deze branch en push naar dan naar git. De test faalt op een bug die ik in die PR gefixt hebt.

**Comment by JennaVergeynst** [comment]
Maar dan zit je wel weer met commits tot in augustus waarschijnlijk ^^. Misschien beter test nu negeren, vanaf de volgende keer werkt het dan als het in master zit!

**Comment by twallema** [comment]
> 
> 
> Maar dan zit je wel weer met commits tot in augustus waarschijnlijk ^^. Misschien beter test nu negeren, vanaf de volgende keer werkt het dan als het in master zit!

Negeren kan, zal inderdaad vanzelf opgelost zijn vanaf de volgende PR.

**Pull request merged**
