### PR TITLE
Implement arenas spatial

### PR DESCRIPTION
**Pull request by mrollier**
* [x] I have checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change
* [x] I made sure all new and existing data sets have a description in the `data/README.md` file
* [ ] I have updated the documentation accordingly.

NOTE: this branch already contains the content of @twallema 's PR137 (which contained an update of `models.sim`)
NOTE: this is my first PR on COVID19-Model, so please be extra critical and inform me on how to improve Git ethics and content of my changes.

Add stochastic spatial SEIRD-extended model that uses spatial information acquired by the `get_COVID19_parameters` function, which has been altered accordingly. One problem that needs to be fixed here is on line 284:
``
coordinates = [read_coordinates_nis(spatial='arr')]
``
This is hardcoded (`arr`) for the time being, but should in fact depend on the the spatial arguments given to `COVID19_SEIRD_sto_spatial(BaseModel)`. Presumably the nis codes should be fetched by the `get_COVID19_parameters` function as well, whose output is an argument of `BaseModel`. Will be fixed later.

Add several functions in `utils` for reading e.g. areas (these functions are expected to become obsolete in later stages)

Add/update several new data files including updated initial populations.

Add notebook `0.1-mrollier-spatial-stochastic-geopandas.ipynb` for the creation of simulation result animations using Geopandas.

Next up I will make functions for plotting purposes out of the methods described in aforementioned Notebook.

### CODE REVIEW

**Comment by JennaVergeynst** [comment]
Thanks for the PR Michiel. First comment: try to always start your local branch from a recently updated master (git pull upstream master), because here I see that you started from a branch or PR by twallema, dating from 14 August…

**Comment by JennaVergeynst** [comment]
Apart from that, looks good! @twallema any comments?

**Comment by twallema** [comment]
@mrollier Is there a demo notebook we can try out?

**Comment by mrollier** [comment]
> @mrollier Is there a demo notebook we can try out?

@twallema I am working on making the functions for plotting more easy to quickly understand (such as the `show_maps` function I just added). This also means that I am building a Notebook that is easy to follow. I spent the better part of today on it and I plan to finish this tomorrow.

**Comment by mrollier** [comment]
I added function for saving and reading `zarr` directories in which simulation results can be stored. This all seems to work fine, but an issue has arisen concerned with the `quantile` function for `xarray` objects:

``
ValueError: dimension 'draws' on 0th function argument to apply_ufunc with dask='parallelized' consists of multiple chunks, but is also a core dimension. To fix, rechunk into a single dask array chunk along this dimension, i.e., ``.chunk({'draws': -1})``, but beware that this may significantly increase memory usage.
``

You can see this problem arise when you go through the Notebook `0.1-mrollier-spatial-stochastic-geopandas` in the subsections "Inspect the results".

This issue is present for all loaded simulations (arrondissement, province and national level) and was *not* there before saving the xarrays in a remote location (i.e. two days ago). Something may have happened in the codec procedure? @stijnvanhoey

**Comment by mrollier** [comment]
WARNING -- I noticed that the `MLE` function in `objective_fcns.py` (and therefore the entire PSO and MCMC) will not work after changing the `parameters` dictionary attribute to a bunch of direct parameters-as-attributes in `base.py`. Will change this back this later.

**Comment by mrollier** [comment]
@JennaVergeynst merged the branch into master. There should be no problems (but make sure to be attentive!)

**Pull request merged**
