### PR TITLE
WIP: time-dependent parameters

### LINKED ISSUE #126: Test run failing
One of the test runs is failing for the moment. @twallema , @jorisvandenbossche , @stijnvanhoey maybe we can meet after holidays to (show us how to) fix this?

### LINKED ISSUE #141: Unifying / generalizing the implementation of checkpoints / compliance (time-dependent parameters)
Currently, the interface to define checkpoints and how those values change through time is somewhat complex to use (especially in optimization).

On the one hand, the user can specify checkpoints like this:

```python
# Create checkpoints dictionary
chk = {
    't':  [60, 120], 
    'Nc': [..., ....]
}
# Run simulation
y = model.sim(total_time, checkpoints=chk)
```

The checkpoint value is given at simulation time, is not a "parameter" as the others, complicating the optimization code. For example, currently some checkpoint values are hardcoded inside the `MLE` definition at https://github.com/UGentBiomath/COVID19-Model/blob/6df47288c11f27ca0aff43b743487a4d3b4542d5/src/covid19model/optimization/objective_fcns.py#L158 

(which is to be able to include the `prevention` parameter in the optimization, where `prevention` determines the values inside the checkpoints dictionary)

But in addition, you can also control *how* the transition from one value to the other (at a checkpoint) goes, using eg a smoother ramp than a simple "jump" in the value. This is done by specifying a `compliance` function at model initialization:

```python
from covid19model.models.compliance import ramp_2
# Initialize the model
model = models.COVID19_SEIRD(initial_states, params, compliance=ramp_2)
```

This compliance function can have additional parameters, and those are automatically added to the model parameters (and can thus also be optimized like other parameters), and has a specific signature (`func(t_since_last_chkp, old, new, **kwargs`).

So to summarize, I think this has some drawbacks:

- The values in the checkpoint dictionary are hard to change as parameter (both the time at which they happen as the value to change to)
- Both the checkpoint as the compliance function together determine the exact value of the parameter in question (typically the interaction matrix), but are defined in two different places (and the interaction is ensure by passing "time since last checkpoint" to the compliance function, putting the responsibility of keeping track of this in the core base model)

---

A possible alternative, that combines both aspects in one, would be to provide the option to specify a *single function* that can control *time-dependent variables*. 

So you could have something like the following (exact keyword names to be discussed, it would be nice to have something shorter as `time_dependent_parameters` ..):

```python

def my_interaction_matrix_evolution(t, param_init, prevention, tau, ...):
    ....
    # use prevention, tau, ... kwargs together with the time to determine interaction matrix
    return Nc

# on model initialization, you specify that this function needs to be used for the Nc parameter of the model
model = models.COVID19_SEIRD(
    initial_states, params, time_dependent_parameters={'Nc': my_interaction_matrix_evolution}
)

# Run simulation doesn't need to pass a checkpoint (this is embodied in the function passed at init)
y = model.sim(total_time)
```

Similarly as with the current `compliance` function, the additional keyword arguments of the time-dependent parameter function can automatically (with some validation) be added to the model's parameter dictionary. And this way, all the checkpoint/compliance-related parameters can be optimized as a normal parameter (so also `prevention`).

For the simple case of just specifying a checkpoints dictionary (without compliance function), the above would be a bit more complex, but we could provide a helper function that turns a checkpoints dictionary into a function with the correct signature and behaviour. Because in the end, the equivalent function for a simple checkpoint `{'t': [t0, t1], 'Nc': [val0, val1]}` is something like:

```python
def func_from_checkpoint(time, param_init):
    if time < t0:
        return param_init
    elif t0 <= time < t1:
        return val0
    else:
        return val1
``` 

so it would be relatively straightforward to generate such a function based on a checkpoints dictionary.

cc @twallema @JennaVergeynst @stijnvanhoey thoughts?

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes #141, closes #126

I only tested it with some small toy models (like in the tests), not yet with the actual SEIRD model. 
Also still need to clean-up the old checkpoints code, and add helper function for simple checkpoints.

### CODE REVIEW

**Review by twallema — COMMENTED** [review]
@jorisvandenbossche I gave the time-dependent parameters concept a try `notebooks/0.1-twallema-calibration-deterministic.ipynb` under 'initialize the model' (edit pushed to the wrong branch, will fix but description below may be enough). They succeed in replicating the behavior of checkpoints + compliance. One thing to keep in mind is the `excess_time/lag_time` concept, I'm uncertain how we will handle this (will thinker about it some more..). 

Briefly summarizing the changes to the workflow below for myself and others. **Previously,** we used to have checkpoints for parameters, with compliance as an additional 'layer' to be applied to a selected parameter (always `Nc`) inside the checkpoints dictionary. The ramp compliance model had the following form,
```
def ramp_1(t,old,new,l,tau):
    # perform interpolation
    if t <= l:
        f = (1/l)*t
    else:
        f = 1.0
    
    return old + f*(new-old)
```
where `t` was the time since the last checkpoint. `old` was the old value of the parameter and `new` was the new value of the parameter. `l` was the slope of the compliance ramp. All the function did was interpolate between an old and a new policy according to a ramp function. The compliance functions were located in `compliance.py`.

The model was then initialized as follows,
```
model = models.COVID19_SEIRD(initial_states, params, compliance=ramp_2)
```
And the policy was changed using a checkpoints dictionary,
```
chk = {
     'time' : [policy_time],
     'Nc' : [Nc_home]
      }
out = model.sim(200, checkpoints= chk)
```
**Now**, this workflow is now replaced by defining one function which handles compliance + policy change. The example below changes the policy from `policy1` to `policy2` according to a 2-parameter delayed ramp (pars `l` and `tau`) on time `policy_change`.
```
def social_policy_func(t,param,policy_time,policy1,policy2,l,tau):
    if t < policy_time:
        return policy1
    else:
        return policy1 + (1/l)*(t-policy_time)*(policy2-policy1)
```
The  parameters `policy1`, `policy2` and `policy_time` must then be added to the dictionary of model parameters.
```
params.update({'policy1': Nc_total,
              'policy2': Nc_home,
              'policy_time': 40})
```
Initialize the model,
```
model = models.COVID19_SEIRD(initial_states, params, time_dependent_parameters={'Nc': social_policy_func})
```
Perform the simulation,
```
out = model.sim(200)
```

**Comment by jorisvandenbossche** [comment]
@twallema thanks for trying it out! 
Your summary sounds fully correct, and do I understand from that that you are happy with the changes and new way of using it?

Some API questions:

- Is the signature of the function OK? (`func(t, param, **extra_params)`) The `param` is the initial value of the parameter (not at timestep t-1, but as initialized for the model object). In your example you are not using it, but I added it because it *might* be useful for certain cases (and if you don't use it, you can simply ignore it as you did)
- Is the name fine? `time_dependent_parameters` is quite long, but also the most explicit / decriptive name I can think of

**Comment by jorisvandenbossche** [comment]
Another question:

- what time value for `t` should be passed? The integer time of a timestamp?

**Comment by twallema** [comment]
> @twallema thanks for trying it out!
> Your summary sounds fully correct, and do I understand from that that you are happy with the changes and new way of using it?
> 
> Some API questions:
> 
> * Is the signature of the function OK? (`func(t, param, **extra_params)`) The `param` is the initial value of the parameter (not at timestep t-1, but as initialized for the model object). In your example you are not using it, but I added it because it _might_ be useful for certain cases (and if you don't use it, you can simply ignore it as you did)
> * Is the name fine? `time_dependent_parameters` is quite long, but also the most explicit / decriptive name I can think of

- Yes, I'm happy with the change. It's a bit more difficult than checkpoints for the end-user, but the optimization and MPC will be easier to use. 
- The signature is ok? What you mean is that `param` is by default the initialized value of the parameter? I didn't know, so not using it was unintentional. But if it works without the user knowing, that's even better? 
- I don't have much inspiration for another name..

**Comment by twallema** [comment]
> Another question:
> 
> * what time value for `t` should be passed? The integer time of a timestamp?

I think the time since the start of the simulation? The back-end works in integer (?) timesteps.

**Comment by JennaVergeynst** [comment]
> Another question:
> 
>     * what time value for `t` should be passed? The integer time of a timestamp?

at any time when a timestamp is possible (or just a string with time for the user), I think this is preferable. If needed with lag-time as an extra parameter to be able to do the math inside the function

**Comment by twallema** [comment]
@jorisvandenbossche Is this update ready for merging or do you want to perform more prototyping (in light of optimization/MPC)?

**Comment by mrollier** [comment]
@jorisvandenbossche what is the reason there are square brackets around `self.stratification` in the fragment of `base.py/_validate_time_dependent_parameters()`?

```
for param, func in self.time_dependent_parameters.items():
            if (param not in (
                self.parameter_names + self.parameters_stratified_names + [self.stratification])
            ):
                raise ValueError(
                    "The specified time-dependent parameter '{0}' is not an "
                    "existing model parameter".format(param))
            kwds = self._validate_parameter_function(func)
            extra_params.append(kwds)
```

With these brackets, @twallema 's example code above malfunctions, but when I delete the square brackets, everything works fine.

**Comment by jorisvandenbossche** [comment]
@mrollier the reason is because, until recently, `self.stratification` was a single string and not a list (while `self.parameter_names` and `self.parameters_stratified_names` are lists, and so to combine them all three in a single list, I converted `self.stratification` in a list of 1 element). 

Now, in the meantime `self.stratification` was changed to be a list, making the above code indeed incorrect. Ideally I should have first updated this PR with the latest changes before it was merged. But I also actually already fixed this here: https://github.com/UGentBiomath/COVID19-Model/pull/161/files#diff-67ef6c0b81f7e0845d52d9a7c9f40bedR90-R95

**Pull request merged**
